### ISSUE TITLE
publish

### ISSUE THREAD

**Issue by ghost** [rtbf-ir/chrome-plugin#2]

**Comment by amirshnll** [comment]
<img width="509" alt="Screen Shot 2022-08-13 at 11 50 05 PM" src="https://user-images.githubusercontent.com/30009591/184507966-50d58dde-fdca-47ab-b95d-5411105894d1.png">

**Comment by amirshnll** [comment]
> <img alt="Screen Shot 2022-08-13 at 11 50 05 PM" width="509" src="https://user-images.githubusercontent.com/30009591/184507966-50d58dde-fdca-47ab-b95d-5411105894d1.png">

hey @dashtaki
Can you tell me what this error is and how to fix it?

**Comment by amirshnll** [comment]
@dashtaki 

Must we publish the Chrome version? Can you assist us in pay the costs? The top error can be fixed using a VPN.

**Comment by ghost** [comment]
I paid for the Chrome Web Store developer account fee.

**Comment by ghost** [comment]
https://chromewebstore.google.com/detail/right-to-be-forgotten/ogijchfghlflmfmdaeeeiondjpdnfilh
